name: Fix Recipe Macros

on:
  schedule:
    # Run every Monday at 3:00 AM UTC
    - cron: '0 3 * * 1'
  workflow_dispatch:
    # Allow manual triggering of the workflow

jobs:
  fix-macros:
    runs-on: ubuntu-latest
    
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Run macro fixer script
        run: |
          python fix_recipe_macros.py --limit 100
      
      - name: Upload log file
        uses: actions/upload-artifact@v3
        with:
          name: recipe-macro-fix-logs
          path: recipe_macro_fix.log