name: Import Facebook Recipes

on:
  workflow_dispatch:
    inputs:
      tagged_file_name:
        description: 'Name of the tagged recipe file to import (in data directory)'
        required: true
        default: 'FB_Recipes_tagged.json'
  push:
    paths:
      - 'data/FB_Recipes_tagged.json'

jobs:
  import-recipes:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Import recipes
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        # Create output directory for logs
        mkdir -p logs
        
        # Check if the input file exists
        input_file="${{ github.event.inputs.tagged_file_name }}"
        if [ -z "$input_file" ]; then
          input_file="data/FB_Recipes_tagged.json"
        else
          input_file="data/$input_file"
        fi
        
        if [ ! -f "$input_file" ]; then
          echo "Error: Input file $input_file not found."
          exit 1
        fi
        
        # Run the import script
        echo "Importing recipes from $input_file..."
        python import_tagged_recipes.py --input "$input_file"
        
    - name: Upload logs
      uses: actions/upload-artifact@v4
      with:
        name: import-logs
        path: logs/