name: Import Custom Recipes

on:
  workflow_dispatch:  # Allows manual triggering
  push:
    paths:
      - 'data/Custom_Recipes.txt'  # Run when recipe file changes

jobs:
  import:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install psycopg2-binary python-dotenv requests beautifulsoup4
      
      - name: Import recipes
        run: |
          # Use the enhanced importer instead of the basic one
          python enhanced_import_custom_recipes.py data/Custom_Recipes.txt data/processed_recipes.json
          
          # Run the recipe metadata updater to ensure complete metadata
          python recipe_metadata_updater.py --limit 100
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          
      - name: Generate summary
        run: |
          echo "## Custom Recipe Import Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Date:** $(date)" >> $GITHUB_STEP_SUMMARY
          echo "- **Source file:** data/Custom_Recipes.txt" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Processed custom recipes and updated metadata for up to 100 recipes with missing data." >> $GITHUB_STEP_SUMMARY