name: Process Facebook URLs

on:
  workflow_dispatch:
    inputs:
      limit:
        description: 'Maximum number of URLs to process (default: 50)'
        required: false
        default: '50'
      force_update:
        description: 'Force update existing recipes'
        required: false
        default: 'false'
        type: boolean

jobs:
  process-facebook-urls:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Verify FB URLs file exists
      run: |
        if [ -f "data/FB URLs.txt" ]; then
          FB_FILE="data/FB URLs.txt"
          echo "✅ Found: data/FB URLs.txt (with space)"
        elif [ -f "data/FB_URLs.txt" ]; then
          FB_FILE="data/FB_URLs.txt"
          echo "✅ Found: data/FB_URLs.txt (with underscore)"
        else
          echo "❌ FB URLs file not found in data/ directory"
          echo "Please upload your FB URLs file as either:"
          echo "  - data/FB URLs.txt (with space)"
          echo "  - data/FB_URLs.txt (with underscore)"
          echo "Current files in data/:"
          ls -la data/ || echo "data/ directory not found"
          exit 1
        fi
        echo "File size: $(wc -l < "$FB_FILE") lines"
        echo "FB_FILE=$FB_FILE" >> $GITHUB_ENV
        
    - name: Process Facebook URLs
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_PORT: ${{ secrets.DB_PORT }}
      run: |
        python enhanced_facebook_scraper.py \
          --file "$FB_FILE" \
          --limit ${{ github.event.inputs.limit || '50' }} \
          --force-update ${{ github.event.inputs.force_update || 'false' }}
        
    - name: Upload processing logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: facebook-processing-logs
        path: |
          enhanced_facebook_scraper.log
          recipe_images/
        retention-days: 7