name: Basic Test

on:
  workflow_dispatch:  # Allow manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Basic environment test
        run: |
          echo "Hello World"
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -la
