name: Update Recipe Database

on:
  workflow_dispatch:
    inputs:
      operation:
        description: 'Operation to perform'
        required: true
        default: 'list'
        type: choice
        options:
          - list
          - search
          - update_image
          - update_title
          - update_complexity
          - batch_update
          - update_from_file

jobs:
  update_recipes:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install psycopg2-binary python-dotenv requests beautifulsoup4
      
      - name: Create .env file
        run: |
          cat > .env <<EOL
          DB_NAME=${{ secrets.DB_NAME }}
          DB_USER=${{ secrets.DB_USER }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          DB_HOST=${{ secrets.DB_HOST }}
          DB_PORT=${{ secrets.DB_PORT }}
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          EOL
      
      - name: Debug directory
        if: ${{ github.event.inputs.operation == 'update_from_file' }}
        run: |
          echo "Current directory: $(pwd)"
          ls -la
          echo "Data directory contents:"
          ls -la data/
      
      - name: Run update from file
        if: ${{ github.event.inputs.operation == 'update_from_file' }}
        run: |
          python update_custom_recipes.py data/Custom_Recipes.txt
      
      - name: Run recipe operation
        if: ${{ github.event.inputs.operation != 'update_from_file' }}
        run: |
          echo "Running operation: ${{ github.event.inputs.operation }}"
          
          case "${{ github.event.inputs.operation }}" in
            "list")
              python run_recipe_operation.py list
              ;;
            "search")
              python run_recipe_operation.py search "${{ github.event.inputs.search_term }}"
              ;;
            "update_image")
              python run_recipe_operation.py update_image "${{ github.event.inputs.recipe_id }}" "${{ github.event.inputs.new_value }}"
              ;;
            "update_title")
              python run_recipe_operation.py update_title "${{ github.event.inputs.recipe_id }}" "${{ github.event.inputs.new_value }}"
              ;;
            "update_complexity")
              python run_recipe_operation.py update_complexity "${{ github.event.inputs.recipe_id }}" "${{ github.event.inputs.new_value }}"
              ;;
            "batch_update")
              python run_recipe_operation.py batch_update "${{ github.event.inputs.csv_path }}"
              ;;
            *)
              echo "Unknown operation: ${{ github.event.inputs.operation }}"
              exit 1
              ;;
          esac