# GitHub Actions Workflow: Update Recipe Images
# Place this file in: .github/workflows/update-images.yml

name: Update Recipe Images

on:
  # Run manually
  workflow_dispatch:
    inputs:
      limit:
        description: 'Maximum number of recipes to process'
        required: false
        default: '50'
        type: string
      method:
        description: 'Method to update images (scraper, direct, search)'
        required: false
        default: 'direct'
        type: choice
        options:
          - scraper  # Uses main.py with registered scrapers
          - direct   # Uses update_recipe_images.py for any site
          - search   # Uses find_recipe_images.py with image search APIs
  
  # Run on schedule (monthly on the first day at 1 AM UTC)
  schedule:
    - cron: '0 1 1 * *'

jobs:
  update-images:
    runs-on: ubuntu-latest
    timeout-minutes: 60  # 1 hour timeout
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Cache Python dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Set up environment variables
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        UNSPLASH_API_KEY: ${{ secrets.UNSPLASH_API_KEY }}
        PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
      run: |
        echo "Environment variables configured"
        
    - name: Check database connection
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
      run: |
        python -c "
        import sys
        sys.path.append('.')
        from database.db_connector import get_db_connection
        try:
            conn = get_db_connection()
            print('✅ Database connection successful')
            conn.close()
        except Exception as e:
            print(f'❌ Database connection failed: {e}')
            sys.exit(1)
        "
        
    - name: Run image update job
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        UNSPLASH_API_KEY: ${{ secrets.UNSPLASH_API_KEY }}
        PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
      run: |
        LIMIT="${{ github.event.inputs.limit || '50' }}"
        METHOD="${{ github.event.inputs.method || 'direct' }}"
        echo "Updating images for up to $LIMIT recipes using $METHOD method"

        if [ "$METHOD" = "scraper" ]; then
          # Use main.py with --update-images flag (uses registered scrapers)
          python main.py --update-images --limit $LIMIT
        elif [ "$METHOD" = "direct" ]; then
          # Use our new direct web scraping approach
          python update_recipe_images.py --limit $LIMIT
        else
          # Use find_recipe_images.py (image search APIs)
          python find_recipe_images.py --update-db --limit $LIMIT
        fi
        
    - name: Generate summary report
      if: always()
      run: |
        echo "## Recipe Image Update Job Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "- **Triggered by:** ${{ github.event_name }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Method:** ${{ github.event.inputs.method || 'direct' }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Limit:** ${{ github.event.inputs.limit || '50' }} recipes" >> $GITHUB_STEP_SUMMARY
        echo "- **Date:** $(date)" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "Check the job logs above for detailed results." >> $GITHUB_STEP_SUMMARY
        
    - name: Notify on failure
      if: failure()
      run: |
        echo "❌ Image update job failed"
        echo "Check the logs above for error details"