# GitHub Actions Workflow: Update Recipe Metadata
# Place this file in: .github/workflows/update_ingredients_workflow.yml

name: Update Recipe Metadata

on:
  # Run manually
  workflow_dispatch:
    inputs:
      limit:
        description: 'Maximum number of recipes to process'
        required: false
        default: '50'
        type: string
  
  # Run on schedule (weekly on Sundays at 2 AM UTC)
  schedule:
    - cron: '0 2 * * 0'

jobs:
  update-metadata:
    runs-on: ubuntu-latest
    timeout-minutes: 60  # 1 hour timeout
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Cache Python dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install beautifulsoup4 requests psycopg2-binary
        
    - name: Set up environment variables
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
      run: |
        echo "Environment variables configured"
        
    - name: Check database connection
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
      run: |
        python -c "
        import sys
        sys.path.append('.')
        from database.db_connector import get_db_connection
        try:
            conn = get_db_connection()
            print('✅ Database connection successful')
            conn.close()
        except Exception as e:
            print(f'❌ Database connection failed: {e}')
            sys.exit(1)
        "
        
    - name: Run recipe metadata update job
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
      run: |
        LIMIT=${{ github.event.inputs.limit || '50' }}
        echo "Processing up to $LIMIT recipes"
        
        # Run the new comprehensive metadata updater
        python recipe_metadata_updater.py --limit $LIMIT
        
        # Also run the original ingredient updater as a backup
        echo "Additionally running the original ingredient updater as a backup..."
        python ingredient_updater.py --limit $LIMIT
        
    - name: Generate summary report
      if: always()
      run: |
        echo "## Recipe Metadata Update Job Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "- **Triggered by:** ${{ github.event_name }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Limit:** ${{ github.event.inputs.limit || '50' }} recipes" >> $GITHUB_STEP_SUMMARY
        echo "- **Date:** $(date)" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "Updated the following metadata fields:" >> $GITHUB_STEP_SUMMARY
        echo "- Ingredients" >> $GITHUB_STEP_SUMMARY
        echo "- Prep time & Cook time" >> $GITHUB_STEP_SUMMARY
        echo "- Servings" >> $GITHUB_STEP_SUMMARY
        echo "- Recipe notes" >> $GITHUB_STEP_SUMMARY
        echo "- Nutrition information" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "Check the job logs above for detailed results." >> $GITHUB_STEP_SUMMARY
        
    - name: Notify on failure
      if: failure()
      run: |
        echo "❌ Recipe metadata update job failed"
        echo "Check the logs above for error details"